- doc/file_names.md
> no byte order mark

- file-formats/chko/examples/z_aff_example_chko.chko.json
Usage of a productive check class should be avoided since we added a 1:1 relation between CHKO and CLAS
> Change implementingClass to an local example class

- abaplint.jsonc
- file-formats/intf/zif_aff_intf_v1.intf.abap
- file-formats/intf/zif_aff_types_v1.intf.abap
changing ENUMS to CONSTANTS, closes #92
> INTF, change ENUMs to CONSTANTS

- file-formats/clas/clas.json
- file-formats/clas/examples/zcl_aff_example.clas.global.abap
- file-formats/clas/examples/zcl_aff_example.clas.json
- file-formats/clas/type/zif_oo_aff_clas_v1.intf.abap
- file-formats/clas/type/zif_oo_aff_clas_v1.intf.json
- file-formats/intf/intf.json
1. Generated new JSON schema automatically
2. Serialised interface with CLASS-type
3. Serialised example class
> Update CLAS Type

- file-formats/chkc/chkc.json
- file-formats/chkc/examples/z_aff_example_chkc.chkc.json
- file-formats/chkc/type/zif_atc_aff_chkc_v1.intf.abap
- file-formats/chkc/type/zif_atc_aff_chkc_v1.intf.json
- file-formats/chko/chko.json
- file-formats/chko/examples/z_aff_example_chko.chko.json
- file-formats/chko/type/zif_atc_aff_chko_v1.intf.abap
- file-formats/chko/type/zif_atc_aff_chko_v1.intf.json
- file-formats/typesUsedForAll/zif_aff_types_v1.intf.abap
1. Generated new JSON schema automatically
2. Serialised interface with CHKC-type/CHKO-type
3. Serialised example class
> Update CHKC and CHKO Type

- doc/specification.md
> doc, remove TABL example

- doc/specification.md
fix typos and remove trailing whitespace
> spec: fix typos

- .github/workflows/linter.yml
> super-linter checks the entire repository 

- file-formats/chko/chko.json
- file-formats/chko/examples/z_aff_example_chko.chko.json
- file-formats/chko/type/zif_atc_aff_chko_v1.intf.abap
> update on CHKO

- doc/specification.md
Note: lines with multiple sentences are bad for code-review, L118
> Specification, see commit msg

- doc/specification.md
> Add examples for camel case notation

- .github/workflows/markdown-link-check.yml
- doc/specification.md
- file-formats/ddls/README.md
> add markdown link check as GH action

- file-formats/fugr/README.md
> readme-fugr

- file-formats/nrob/README.md
> readme-nrob

- file-formats/chko/README.md
> readme-chko

- file-formats/fugr/README.md
> add LINKs of FUNC

- file-formats/chkv/README.md
> readme chkv

- file-formats/enho/enho.json
Here was an error that affected the indentation. I have regenerated the schema.
> Fix schema for ENHO

- file-formats/enhs/README.md
> readme-enhs

- file-formats/enho/README.md
> readme-enho

- file-formats/ddls/README.md
> readme-ddls

- file-formats/chko/chko.json
- file-formats/clas/clas.json
- file-formats/fugr/func.json
- file-formats/intf/intf.json
> Set "uniqueItems": true for tables with unique key

- file-formats/intf/README.md
- file-formats/intf/examples/z_aff_example_intf.intf.json
- file-formats/intf/intf-v1.json
New JSON Schema and data for the object type INTF, that shows how we defined JSON versioning in ABAP file formats.
> How JSON versioning is defined (here: INTF)

- docs/decision-log/0001-json-version.md
- json-validator.py
> Validation JSON Schema - JSON Data broken

- docs/json.md
> there is one JSON file per ABAP object

- docs/json.md
> Update documentation about `additionalProperties`

- file-formats/doma/doma-v1.json
In #286 we forgot to update the JSON Schema.
[Maybe we can have an automatism for this generation.]
> Generate JSON Schema from ABAP type

- docs/json.md
Closes #300
I added a remark that enums should not be used without initial value, required or default
> Update JSON specification

- file-formats/sajc/examples/z_aff_example_sajc.sajc.json
- file-formats/sajt/README.md
- file-formats/sajt/examples/z_aff_example_sajt.sajt.json
> [SAJ*] Example for SAJC and SAJT

- file-formats/clas/clas-v1.json
- file-formats/fugr/fugr-v1.json
- file-formats/intf/intf-v1.json
- file-formats/zif_aff_types_v1.intf.abap
change title and description of Abap language version in if_aff_types_v1 and therefore regenerating the schemas of intf, clas and fugr
> change Abap language version in if_aff_types

- file-formats/aplo/aplo-v1.json
- file-formats/aplo/examples/z_aff_example_aplo.aplo.json
- file-formats/aplo/type/zif_aff_aplo_v1.intf.abap
Change sub_objects to subobjects
> [APLO] Update type

- file-formats/chkc/chkc-v1.json
- file-formats/chkc/type/zif_aff_chkc_v1.intf.abap
- file-formats/chko/chko-v1.json
- file-formats/chko/type/zif_aff_chko_v1.intf.abap
- file-formats/chkv/chkv-v1.json
- file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
See #320. This fixes CHKC, CHKO and CHKV
> Update ABAP language version for CHKC, CHKO, CHKV

- file-formats/chdo/chdo-v1.json
- file-formats/chdo/examples/z_aff_example_chdo.chdo.json
- file-formats/chdo/type/zif_aff_chdo_v1.intf.abap
We decided to rename the attribute. Changes are already applied in dev system.
> [CHDO] Renaming an attribute

- file-formats/aobj/README.md
- file-formats/aobj/examples/z_aff_example_aobj.aobj.json
> [AOBJ] Add example

- .github/workflows/editorconfig.yml
- .github/workflows/py-validation.yml
updating to 3.7 seems to work
for more information see https://github.com/actions/setup-python/issues/544
> actions: update python

- file-formats/ddls/ddls-v1.json
- file-formats/ddls/type/zif_aff_ddls_v1.intf.abap
> DDLS: Write description in sentence style

- file-formats/ddls/type/zif_aff_ddls_v1.intf.abap
As it's a name it's also capitalized even in descriptions / sentences.
Fixes #443
> DDLS: Service Consumption Model is a name

- file-formats/ront/ront-v1.json
- file-formats/ront/type/zif_aff_ront_v1.intf.abap
- fixes issue #459 
- new type category added: "Dependent Object"
> [RONT] Update files for RONT

- requirements.txt
Fixes https://github.com/SAP/abap-file-formats/security/dependabot/2
> Update requirements to GitPython 3.1.30

- file-formats/ddls/ddls-v1.json
> DDLS: Service Consumption Model to Title Style

- file-formats/ntta/ntta-v1.json
closes https://github.com/SAP/abap-file-formats/issues/473
> [NTTA] fix case

- file-formats/dsfi/examples/z_aff_example_dsfi_ana.dsfi.json
- file-formats/ntta/examples/z_aff_example_ntta.ntta.json
- file-formats/ntty/examples/z_aff_example_ntty.ntty.json
- json-validator.py
workaround for #479 that improves the validation and fixes the JSON data by educated guess.
> Fix the JSON data validation

- json-validator.py
closed #479 
Logic: For every JSON Schema we find the JSON data/example and create a match. All matches then, are validated.
Needs some rework, once there will be other formatVersions than `1` :)
> Make validation of JSON data more robust

- file-formats/clas/clas-v1.json
- file-formats/clas/type/zif_aff_clas_v1.intf.abap
Refers to #396
Also found some title that have not been in title case
> [CLAS] Give enum a default

- file-formats/intf/intf-v1.json
- file-formats/intf/type/zif_aff_intf_v1.intf.abap
Refers to #396
Also found some title case issue
> [INTF] Set enum default

- file-formats/fugr/examples/z_aff_example_fugr.fugr.z_aff_example_func.func.json
- file-formats/fugr/fugr-v1.json
- file-formats/fugr/func-v1.json
- file-formats/fugr/type/zif_aff_fugr_v1.intf.abap
- file-formats/fugr/type/zif_aff_func_v1.intf.abap
> [FUGR, FUNC] Set enum default

- file-formats/smbc/smbc-v1.json
- file-formats/smbc/type/zif_aff_smbc_v1.intf.abap
- file-formats/smbc/type/zif_aff_smbc_v1.intf.json
Note: the commit text is incorrect, it should be 2302
> SAP BTP 2302 updates for SMBC file format

- requirements.txt
> Update Version of jsonschema

- README.md
> Add Tooling section to README

- file-formats/chkv/chkv-v1.json
- file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
> [CHKV] Fix length of parameter names

- generate/cl_run.clas.abap
Refer to https://github.com/SAP/abap-file-formats-tools/pull/269
> Fix cl_run.clas.abap

- README.md
- docs/glossary.md
- docs/specification.md
> Definition of ABAP Repository Objects

- abaplint.jsonc
- file-formats/aobj/type/zif_aff_aobj_v1.intf.abap
- file-formats/aplo/type/zif_aff_aplo_v1.intf.abap
- file-formats/cdbo/type/zif_aff_cdbo_v1.intf.abap
- file-formats/cfdf/type/zif_aff_cfdf_v2.intf.abap
- file-formats/chko/type/zif_aff_chko_v1.intf.abap
- file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
- file-formats/dobj/type/zif_aff_dobj_v1.intf.abap
- file-formats/dsfi/type/zif_aff_dsfi_v1.intf.abap
- file-formats/eeec/type/zif_aff_eeec_v1.intf.abap
- file-formats/enho/type/zif_aff_enho_v1.intf.abap
- file-formats/enhs/type/zif_aff_enhs_v1.intf.abap
- file-formats/evtb/type/zif_aff_evtb_v1.intf.abap
- file-formats/fugr/type/zif_aff_func_v1.intf.abap
- file-formats/gsmp/type/zif_aff_gsmp_v1.intf.abap
- file-formats/ilmb/type/zif_aff_ilmb_v1.intf.abap
- file-formats/nont/type/zif_aff_nont_v1.intf.abap
- file-formats/ntta/type/zif_aff_ntta_v1.intf.abap
- file-formats/ntty/type/zif_aff_ntty_v1.intf.abap
- file-formats/sfpf/type/zif_aff_sfpf_v1.intf.abap
- file-formats/sito/type/zif_aff_sito_v1.intf.abap
- file-formats/smbc/type/zif_aff_smbc_v1.intf.abap
- file-formats/sprv/type/zif_aff_sprv_v1.intf.abap
- file-formats/srvb/type/zif_aff_srvb_v1.intf.abap
- file-formats/susi/type/zif_aff_susi_v1.intf.abap
- file-formats/uipg/type/zif_aff_uipg_v1.intf.abap
- file-formats/uist/type/zif_aff_uist_v1.intf.abap
- file-formats/zif_aff_types_v1.intf.abap
fixes #616
AFAIK: This is not a policy that can be achieves by ADT in Eclipse. So there might/will be regressions :unamused:
> Align spaces

- docs/json.md
> Add recommendation for `$required` regarding boolean fields

- docs/specification.md
> Add file type XDP

- docs/json.md
Just a small improvement of the text based on feedback provided by @Lindafchsl
> Improve AFF Defaults Documentation

- generate/package-lock.json
- generate/package.json
updating for https://github.com/SAP/abap-file-formats/pull/717
> update npm dependencies
