file-formats/intf/zif_aff_intf_v1.intf.abap, file-formats/intf/zif_aff_types_v1.intf.abap
With 16+ years in ABAP I'm a newbie, and I have trouble reading the source code, this refactors INTF and removes all INCLUDE STRUCTURE, hopefully making it easier for humans to read.
It does however, sacrifice some reuse and introduces a bit of duplication, but IMHO its okay
Note that the `schema` field is removed from the header! `$schema` is not a json schema property, its a thing implemented in some editors like vscode. Editors have mechanisms to identify the correct schema for a file, I don't think we want to persist a URL inside the files, it might change in the future.
single definitions refactored to abapdoc + ABAP, instead of ABAP + abapdoc + ABAP, to
```abap
"! Language
TYPES language TYPE c LENGTH 2.
```
from
```abap
TYPES:
"! Language
language TYPE c LENGTH 2.
```
which also …
=> refactor INTF

README.md
In the readme the object types ENHO and ENHS were missing in the list of supported object types.
=> Add missing supported object types to readme

abaplint.jsonc
If ENUMS are not required, we can change the language version to 702
can be merged after https://github.com/SAP/abap-file-formats/pull/95 is merged
=> Change language version v751 to v702

README.md
I think it will be tedious to maintain this list, there is a link to the folder already where the list of supported objects can be found
=> README: remove list of supported objects

file-formats/clas/examples/zcl_aff_example.clas.json
The field `category` is not tagged with `$required` or `$showAlways`. Hence, category `generalObjectType` (ABAP Type 00) shall not be written in serialization process.
=> CLAS: Correct example

abaplint.jsonc, file-formats/clas/type/zif_oo_aff_clas_v1.intf.abap, file-formats/intf/intf.json, file-formats/intf/type/zif_oo_aff_intf_v1.intf.abap, file-formats/typesUsedForClasAndIntf/zif_oo_aff_types_v1.intf.abap, file-formats/typesUsedForClasAndIntf/zif_oo_aff_types_v1.intf.json
Interface zif_oo_aff_types_v1 was added
=> Add interface for types used by CLAS & INTF

file-formats/chkv/chkv.json, file-formats/chkv/examples/z_aff_example_chkv.chkv.json, file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
Remove a non-required parameter in the file format definition for ABAP type CHKV
TODO:
=> rm type in chkv

file-formats/clas/format.md
The term "ABAP in Eclipse" is not an offical term. The official name
is "ABAP Development Tools".
=> "ABAP in Eclipse" is not a SAP-official term

doc/specification.md
=> Document Reusable Fields

doc/specification.md
The filename pattern in the specification was not correct: `<content_type>` and `<language>` are independent of each other.
=> Fix filename pattern in specification

doc/001-json-version.md, doc/decision-log/0001-json-version.md, doc/decision-log/index.md, doc/decision-log/template.md
The Markdown documents provide information of design decision of the `versioning` of JSON files in ABAP file formats.
It contains the considered alternative options and pros/cons we discussed.
It contains discussions from #53
It also includes a index.md as a landing page for further design decision documents
=> Add decision-record

file-formats/intf/examples/z_aff_example_intf.intf.abap, file-formats/intf/examples/z_aff_example_intf.intf.json
`cx_static_check` is unknown to the linter, as it runs without deps
I think its okay to remove `cx_static_check` as its not critical to the example
found during regression test of the next abaplint version, https://github.com/abaplint/abaplint/pull/2220
=> INTF: update example

file-formats/nrob/examples/z_aff_nr.nrob.json, file-formats/nrob/nrob-v1.json, file-formats/nrob/type/zif_aff_nrob_v1.intf.abap
Now, the type of bufferedNumbers is integer with minimum 0 and maximum 99999999. This corresponds to former type n length 8.
=> Change type of bufferedNumbers to integer

docs/json.md
We decided **not** to write a default title or a default description if no title or description is provided. This had to be updated in our documentation.
=> Delete part with default title and description

abaplint.jsonc
if opening the example files in vscode, they are added to the registry and errors are shown
this should fix that no files under "/examples/" are ever taken into account
@schneidermic0 try this
=> dont report abaplint errors for examples

json-validator.py
Logic introduced in efd04e1 did not account for broken JSON data.
The error message was set correctly, but the exception was not caught, hence no helpful validation.
Observed in #317
=> Catch exception when JSON data is not decoded

file-formats/enhs/enhs-v1.json, file-formats/enhs/type/zif_aff_enhs_v1.intf.abap, file-formats/zif_aff_types_v1.intf.abap
In ENHS, an enum type without a default or initial component was used. I suggest to make the component required.
=> [ENHS] Make enum type required

docs/json.md
Now, enum values can be overwritten by using an annotation. I updated the documentation to describe the procedure
closes #312
=> Update documentation for overwriting enum values

file-formats/chkv/chkv-v1.json, file-formats/chkv/examples/z_aff_example_chkv.chkv.json, file-formats/chkv/type/zif_aff_chkv_v1.intf.abap
=> CHKV: Remove required fields `low` and `high`

docs/json.md
Documentation of mapping between ABAP type and JSON Schema was missing.
Closes #365
=> Document ABAP Type Mapping

.gitattributes
With github/linguist#4614 Github understands "asddls" files and uses
the syntax coloring provided by
https://github.com/FreHu/abap-cds-grammar
Let's use an override for this repo so that acds files just use the
existing coloring for "asddls".
This is explained in:
https://github.com/github/linguist/blob/master/docs/overrides.md
Fixes: #371
=> Use ABAP CDS Syntax Highlighter for .acds files

docs/json.md
We just had a discussion that it is crucial to consider the default handling during serialization and deserialization. Otherwise, there might be a mix-up with initial values.
Let's update the documentation with this information.
=> Consider default values in ABAP file formant implementations

docs/json.md
We want to forbid hashed tables, because we do not see any advantage in the AFF. If later there will be use cases, we can remove this limitation.
This is a proposal for issue #176
=> Forbid hashed tables in AFF

abaplint.jsonc, file-formats/zif_aff_types_v1.intf.abap
Object type CFDF needs a header without ABAP language version.
See #401
=> New header without ABAP language version

README.md
The URL has constantly issues with its availability. Since our checks require the availability, we could silence this particular URL.
=> Don't check for 'api.reuse' availabilit

.github/workflows/editorconfig.yml, .github/workflows/markdown-link-check.yml, .github/workflows/py-validation.yml
check markdown + editorconfig + json actions:
only run on pull request, note that the these checks are required, plus its required that branches are up to date, and main is protected
ie. its only needed to run on pull request
this gives 3 action results,
instead of 6,
for each commit
plus set permissions and timeout
=> run less actions

file-formats/ddls/ddls-v1.json, file-formats/ddls/type/zif_aff_ddls_v1.intf.abap
The official term for source type "v" is "DDIC-Based Views". So let's also use it here.
=> DDLS: Use Official Terms for "sourceType" Attribute

docs/json.md
With this change, we specify that adding values to an enum field is only compatible if a default value is specified. If not, it is not a compatible change and format version has to be increased.
Closes #457
=> Update compatibility rules

.github/workflows/generate.yml, file-formats/aobj/aobj-v1.json, generate/abap_transpile.json, generate/aff.mjs, generate/package-lock.json, generate/package.json
github action will now give an error if the ABAP code and generated schema does not match
Note that "Generate Schemas" is not a required status check, so it will not block merges
ENHO skipped due to https://github.com/SAP/abap-file-formats/issues/409
=> github actions: issue error if mismatch ABAP <> Schema

.github/workflows/py-validation.yml, json-validator.py
I suggest to change the error message for a missing field "formatVersion" to "JSON Example does not specify the field "formatVersion"".
Additionally, let's rename improve the action title.
Refs #479
=> Improved error messages for missing "formatVersion"

file-formats/enho/enho-v1.json, file-formats/enho/type/zif_aff_enho_v1.intf.abap
Refers to #396
Also found some title case issue
=> [ENHO] Give enum default

file-formats/fugr/func-v1.json, file-formats/fugr/reps-v1.json, file-formats/fugr/type/zif_aff_func_v1.intf.abap, file-formats/fugr/type/zif_aff_reps_v1.intf.abap
For REPS and FUNC, defaults for the enums are set. This allows compatible extensions of the enum values.
=> [FUGR] Set enum defaults for compatibility

file-formats/evtb/evtb-v1.json, file-formats/evtb/type/zif_aff_evtb_v1.intf.abap
The length of field `bo_operation `is increased from 18 to 30 characters. 
A downport (e.g. via abapGit) of an event binding to an onPremise system with an outdated JSON schema for object type Event Binding will fail, if the bo_operation length exceeds 18 characters. 
Should this need arise, the necessary update to the JSON Schema and AFF interface will be provided in the form of a note.
=> [EVTB] Update files for increased bo_operation length

file-formats/nont/examples/z_aff_example_nont.nont.json, file-formats/nont/nont-v1.json, file-formats/nont/type/zif_aff_nont_v1.intf.abap
* The expanded name has become obsolete for object type NONT is therefore deleted from the AFF interface.
* The title for the field `root_node_flag` is changed from "Root Node Flag" to "Root Node" in response to feedback from a UX review. 
This second improvement is visible in the form-based editor for object type NONT in ABAP Development Tools. 
Renaming also the field `root_node_flag` in the NONT AFF-interface is planned, but will probably be realized in the second AFF version accompanied by appropriate compatibility handling.
=> [NONT]: Delete expanded name and update root node title

json-validator.py
Will provide a message, instead of abortion, for the error in #526 (example name missing object type).
=> Catch exception if json schema not found

file-formats/nont/examples/z_aff_example_nont.nont.json, file-formats/nont/nont-v1.json, file-formats/nont/type/zif_aff_nont_v1.intf.abap
* the boolean root_node_flag field is renamed to root_node in the AFF interface.
* the obsolelete expanded name is removed from the ABAP File Format for SAP Object Node Type (NONT)
=> Rename field root_node_flag and delete obsolete expanded_name

file-formats/cdbo/examples/zcdb_adt_test.cdbo.json, file-formats/cdbo/type/zif_aff_cdbo_v1.intf.abap
Reverts SAP/abap-file-formats#549
CDBO cannot do the change because hotfix can not be provided. I will revert this change
=> Revert "[CDBO] Change Value for CDS Types"

file-formats/sajc/README.md, file-formats/sajc/examples/z_aff_example_sajc.sajc.json, file-formats/sajc/sajc-v1.json, file-formats/sajc/type/zif_aff_sajc_v1.intf.abap
A new type of class-based application jobs is introduced. Here, the title of the parameter, the screen element which is used for the parameter and the radio button group are not set in the class any more, but in the application job catalog entry. Therefore, the application job catalog entry has to be extended.
=> [SAJC] Add title, screen element and radiobutton group to parameters

file-formats/ront/README.md, file-formats/ront/examples/z_aff_example_ront.ront.json, file-formats/ront/ront-v1.json, file-formats/ront/type/zif_aff_ront_v1.intf.abap
The AFF interface for SAP Object Type (RONT) is extended by two new optional fields:
* interface_behavior_definition
* odm_entity_name
These fields make it possible to relate an existing SAP Object Type to a One Domain Model (ODM) entity and / or [Interface Behavior Definition](https://help.sap.com/doc/abapdocu_latest_index_htm/latest/en-US/abenbdl_rap_bo_interface.htm?file=abenbdl_rap_bo_interface.htm), thus enriching the SAP Object Type's integration possibilities.
=> [RONT] Add ODM Entity Name and Interface Behavior Definition to RONT AFF

generate/aff.mjs, generate/cl_run.clas.abap
closes #603 
Console log/output of the GitHub Action
Before
After
=> Generate JSON Schema for formatVersion != 1 

compatibility-check/json-schema-diff.js
Sort out the non-relevant JSON Schema right at the beginning, so we don't need to catch those kind of failures later. E.g. line 27-28 will be removed by this change
=> Consider modified JSON Schema only

docs/json.md
This adds documentation for the new annotation `$pattern` in https://github.com/SAP/abap-file-formats-tools/pull/312 
Fixes #626
=> add documentation for $pattern annotation 

docs/json.md
JSON schema specification recommends to only use the subset documented [here](https://json-schema.org/understanding-json-schema/reference/regular_expressions).
With this change, this is (hopefully) clearer
=> Emphasize the recommended syntax of regex

docs/json.md
In the example I used for the pattern annotation I had a typo in the pattern; [a-Z]* is not a valid regex, therefore I changed it to [a-z]*
=> Fix incorrect example in docs/json.md documentation

.editorconfig
Your GitHub Actions are defined in YML files which shall have an empty line as EOF marker.
=> Add yml to .editorconfig

file-formats/aifr/aifr-v1.json, file-formats/aifr/examples/z_aff_example_aifr.aifr.json, file-formats/aifr/type/zif_aff_aifr_v1.intf.abap
Short explanation of the background:
During our tests, we discovered the need for an additional field in the AIFR, specifically the AIF Recipient. 
It must be possible to assign the same AIF recipient to different namespaces.
The object name is derived from the namespace and the AIF Recipient. To ensure accurate derivation, we include both fields in the creation wizard and set the object name as read-only.
Since the exact derivation from object name Recipient back to Namespace and AIF Recipient may not always be possible, we displayed both fields as read-only in the editor for informational purposes.
=> [AIFR] - Adding field aifRecipient to AFF for AIFR

abaplint.jsonc, docs/json.md
=> Add Naming Conventions for AFF Interfaces to Documentation

.github/workflows/markdown-link-check.yml
Downgrading action runner to ubuntu 22.04 as proposed in https://github.com/UmbrellaDocs/action-linkspector/issues/32.
It seems like a fix is already proposed for the GitHub action, but it is not merged yet: https://github.com/UmbrellaDocs/action-linkspector/pull/34.
=> Temporary fix for linkspector GitHub action

.github/workflows/generate.yml
> Starting January 30th, 2025, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact)
see https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
I've updated this to v4, but do we really need to save the generated schemas in the action? The only thing this does is to save the generated schemas in the action workflow (e.g. [here](https://github.com/SAP/abap-file-formats/actions/runs/13035151280), scroll to the bottom). 
fixes issue in #677
=> Update actions/upload-artifact to v4

.github/workflows/example-not-delted.yml
Increase version for `tj-actions/changed-files` from 44 to 46. 
Fixes https://github.com/SAP/abap-file-formats/security/dependabot/13
=> Increase Version for `tj-actions/changed-files` from 44 to 46

.github/workflows/example-not-delted.yml
As tj-actions owners did not prove to have safeguarded their organization, it is better to not trust the organization anymore.
=> chore: Change from tj-actions/changed-files to step-security/changed-files

file-formats/ddls/ddls-v1.json, file-formats/ddls/type/zif_aff_ddls_v1.intf.abap
Source type can also be "External Entity"
=> DDLS: Add "External Entity"

generate/cl_run.clas.abap, generate/package-lock.json, generate/package.json
Github Action for comparing generated with provided JSON schema broke due to some dependency updates in abap-file-format-tools and the abaplint transpiler (see https://github.com/SAP/abap-file-formats/actions/runs/16568936840/job/46856004071?pr=713).
After updating the npm dependencies in this repository too, the transpiler reported new syntax errors in the `cl_run` class. Are this intended side effects or regression bugs from the transpiler @larshp?
After fixing the syntax errors, the GitHub Action is working again.
=> Update npm dependencies and fix syntax
